spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin@123
    url: jdbc:postgresql://localhost:5432/ecommerce_db

  data:
    redis:
      host: localhost
      port: 6379
      password: admin@123

application:
  security:
    jwt:
      signing-key: 5heUCJxsTsaYyTE6+XB+tnpvdZkttNv5PBWHe9v9q73kGjDa2+UI2YQMWPj1Fpec
      expiration-ms: 600000 # 10 minutes


stripe:
  api-key: sk_test_51ShYsBFIOgharRgILUZniUK5LMfNDjj8Bzs7pBMPYbQYYE04upl7Cj9RHYFG0BseDD72lCZuSgoDQvNF7QmvQ3uU00TPRFWTpu
  success-url: http://localhost:8080/api/v1/payments/success?session_id={CHECKOUT_SESSION_ID}
  cancel-url: http://localhost:8080/api/v1/payments/cancel
  currency: bdt